on:
  push:
    branches:
      - jana




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before folder contents'
        run: ls
      - uses: actions/checkout@v3
      - name: 'after folder contents'
        run: ls